{% set name = "murmurhash" %}
{% set version = "1.0.2" %}
{% set sha256sum = "c7a646f6b07b033642b4f52ae2e45efd8b80780b3b90e8092a0cec935fbf81e2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256sum }}

build:
  number: 0
  script: python -m pip install --ignore-installed --no-deps -v .
  skip: True  # [win32 or linux32]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - msinttypes  # [win and py<35]
    - python
    - pip
    - wheel
  run:
    - python

test:
  requires:
    - pytest

about:
  home: https://github.com/explosion/murmurhash/
  license: MIT
  license_file: LICENSE
  summary: Cython bindings for MurmurHash2

extra:
  recipe-maintainers:
    - rmax
