{% set name = "murmurhash" %}
{% set version = "1.0.13" %}
{% set sha256sum = "737246d41ee00ff74b07b0bd1f0888be304d203ce668e642c86aa64ede30f8b7" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256sum }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [win32 or linux32]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - msinttypes  # [win and py<35]
    - cython
    - python
    - pip
    - setuptools
    - wheel

  run:
    - python

test:
  requires:
    - pytest
  imports:
    - murmurhash
    - murmurhash.mrmr

about:
  home: https://github.com/explosion/murmurhash/
  license: MIT
  license_file: LICENSE
  summary: Cython bindings for MurmurHash2

extra:
  recipe-maintainers:
    - rmax
    - conda-forge/spacy
