{% set name = "murmurhash" %}
{% set version = "1.0.4" %}
{% set sha256sum = "422084ac1fe994cb7c893689c600923dee4e2c3fc74e832f7d9a8d6fdcc362d5" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256sum }}

build:
  number: 2
  script: python setup.py install --single-version-externally-managed --record=record.txt
  skip: true  # [win32 or linux32]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - msinttypes  # [win and py<35]
    - python
    - pip
    - setuptools

  run:
    - python

test:
  requires:
    - pytest
    - mmh3
  imports:
    - murmurhash
    - murmurhash.mrmr
  commands:
    - python -m pytest --tb=native --pyargs {{ name }}

about:
  home: https://github.com/explosion/murmurhash/
  license: MIT
  license_file: LICENSE
  summary: Cython bindings for MurmurHash2

extra:
  recipe-maintainers:
    - rmax
    - ines
    - honnibal
    - adrianeboyd
