schema_version: 1

context:
  name: murmurhash
  version: "1.0.14"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: dd5a31d995b8ae7c2179f9752f4e0800b020230edfb81f45f8841f8a5abafc18

build:
  number: 0
  skip: win32 or linux32 or match(python, '>=3.14')
  script: ${{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - cython
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
  host:
    - if: win and match(python, "<3.5")
      then: msinttypes
    - cython
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

tests:
  - python:
      imports:
        - murmurhash
        - murmurhash.mrmr
      pip_check: true
  - requirements:
      run:
        - pytest
    script:
      - python run_test.py
    files:
      recipe:
        - run_test.py


about:
  license: MIT
  license_file: LICENSE
  summary: Cython bindings for MurmurHash2
  homepage: https://github.com/explosion/murmurhash/

extra:
  recipe-maintainers:
    - rmax
    - conda-forge/spacy
    - synapticarbors
