schema_version: 1

context:
  name: murmurhash
  version: 1.0.13

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 737246d41ee00ff74b07b0bd1f0888be304d203ce668e642c86aa64ede30f8b7

build:
  number: 0
  skip: win32 or linux32 or match(python, '>=3.14')
  script: ${{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  build:
    - if: build_platform != target_platform
      then: 
      - python
      - cross-python_${{ target_platform }}
      - cython
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
  host:
    - if: win and match(python, "<3.5")
      then: msinttypes
    - cython
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

tests:
  - python:
      imports:
        - murmurhash
        - murmurhash.mrmr
      pip_check: true
  - requirements:
      run:
        - pytest
    script:
        - run_test.py

about:
  license: MIT
  license_file: LICENSE
  summary: Cython bindings for MurmurHash2
  homepage: https://github.com/explosion/murmurhash/

extra:
  recipe-maintainers:
    - rmax
    - conda-forge/spacy
    - synapticarbors
