appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: default, linux_ppc64le: default}
travis:
  secure: {BINSTAR_TOKEN: IqAYJVjYFgWOE5KiDOe/pvXwWBeYtybqWVyqGuB1E8BYe8vS7L5z2cLO23IPB961gNoQzjDyRNMTmBDORWcG17OctvCXGKVIGr7bi61juf8p22acP0+XC4cEDTkXxNqZ8wvl1bi1O7yn+iMEDZIAupUn/XvlvREwezxw09oFN2afOsAFKmuK+UyPu/gcNjdUy7KapB2+ZGbEt86QXv2cQSUQAMyAiMamel3muAxdzkZlKSKWhih7oqGCDWPVYdwY3OYCP/i5rQ3elV2UZQFytSt0BPGx1cgh8tYRBXEBl2NyQ69imzPZuBOElrrMF8jykYCkS5gcC3peKBCtSjBQLteLaSycdK1zhyKA2Aw0ylvGslhnLTLQ8okdmB6Gg30MBcf9UWDuFMG4GcoJhG5tvrRGLu09eaCzS5XE7VriysGsALknEhao9tZFQveTLVBl3+drk8Vv8YeimWEg60x+JZB+0Of7aI7iTMncADTyvfjRuzaGMY/57t8ue4SsJZ4m+h2u6PiyTBIdTkZkgudRPjUsXRwJG45bEZoTGZ53mWGChK0xpdgH5O8U0vfyzhSU6q396MJaluf1rX6wLb4wQQA0HuA73mXh+NrRlkaNtoznC99AinJdV5XN3OBMpJHvY+EVESkLhjMrJyacGM/9fuCAvSShIeuALa/cCNz3PrE=}
